CREATE DATABASE IF NOT EXISTS db_100_1;
CREATE DATABASE db_100_2;
CREATE DATABASE db_100_3;
CREATE DATABASE db_1000_1;
CREATE DATABASE db_1000_2;
CREATE DATABASE db_1000_3;
CREATE DATABASE db_10000_1;
CREATE DATABASE db_10000_2;
CREATE DATABASE db_10000_3;

USE db_100_1;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-100.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-100-3-4.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_100_2;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-100.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-100-5-4.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_100_3;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-100.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-100-10-3.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_1000_1;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-1000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-1000-5-4.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_1000_2;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-1000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-1000-10-4.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_1000_3;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-1000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-1000-50-3.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_10000_1;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-10000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-10000-5-3.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_10000_2;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-10000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-10000-50-3.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

USE db_10000_3;

CREATE TABLE A(
    A1 INT,
    A2 varchar(150)
);
CREATE TABLE B(
    B1 INT,
    B2 INT,
    B3 varchar(150)
);

LOAD DATA LOCAL INFILE 'dbs/A-10000.csv'
INTO TABLE A
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'dbs/B-10000-500-1.csv'
INTO TABLE B
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
